CREATE TABLE POWER_CONTROL(POWER_ITEM VARCHAR2(20) NOT NULL, POWER_STATE NUMBER(10) NOT NULL);


INSERT INTO POWER_CONTROL(POWER_ITEM, POWER_STATE) 
VALUES('powerLamp', '1');

INSERT INTO POWER_CONTROL(POWER_ITEM, POWER_STATE) 
VALUES('powerCamping', '1');

INSERT INTO POWER_CONTROL(POWER_ITEM, POWER_STATE) 
VALUES('powerToilet', '1');

INSERT INTO POWER_CONTROL(POWER_ITEM, POWER_STATE) 
VALUES('powerOffice', '1');


SELECT * FROM POWER_CONTROL;

DESC POWER_CONTROL;